### 1.1 函数对象与实例对象

1.  new 函数产生的对象,称为实例对象,简称对象
2.  将函数作为对象使用时,简称函数对象

```javascript
function Fn() {} //Fn函数
const fn = new Fn(); //Fn是构造函数,fn是实例对象
console.log(Fn.prototype); //Fn函数对象
Fn.bind({}); //Fn函数对象
$('#test'); //jQuery函数
$.get('/test'); //jQuery函数对象
function Person(params) {}
```

### 1.2 两种类型的回调函数

#### 同步回调

1. 理解:立即执行,完全执行完了才结束,不会放入回调队列
2. 例子:数组遍历相关回调函数 Promise 的 excutor 函数

```javascript
//1.同步回调函数
const arr = [1, 3, 5];
arr.forEach((item) => {
    //遍历回调
    console.log(item);
});
console.log('forEach()之后');
// 1
// 3
// 5
// forEach()之后
```

#### 异步回调

1. 理解:不会立即执行,会放入回调队列中将来执行
2. 例子:定时器回调/ajax 回调/ Promise 的成功|失败回调

```javascript
//2.同步回调函数
setTimeout(() => {
    //同步回调函数,会放入队列中将来执行
    console.log('timout callback()');
}, 0);
console.log('setTimeout()之后');
//setTimeout()之后
//timout callback()
```

### 1.3 JS 的 error 的处理

mdn 文档:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error

1.  错误的类型

    -   \*\* Error:所有错误的父类型
    -   \*\* TypeError:数据类型不正确
    -   \*\* ReferenceError:引用的变量不存在
    -   \*\* RangeError:数据值不在其所允许范围
    -   \*\* SyntaxError:语法错误

    -   EvalError:错误的原因：与 eval() 有关
    -   InternalError:创建一个代表 Javascript 引擎内部错误的异常抛出的实例
    -   URIError:错误的原因：给 encodeURI()或 decodeURl()传递的参数无效

2.  错误处理
    捕获错误:try...catch

    ```javascript
    try {
        let d;
        console.log(d.xxx);
    } catch (error) {
        console.log(error);
        console.log(error.message);
        console.log(error.stack);
    }
    ```

    抛出错误 :throw error

3.  错误对象
    message 属性:错误相关信息
    stack 属性:函数调用栈记录信息

    ```javascript
    function something() {
        if (Date.now() % 2 === 1) {
            console.log('当前时间为奇数,可以执行任务');
        } else {
            throw new Error('当前时间为偶数,不可以执行任务');
        }
    }
    try {
        something();
    } catch (error) {
        console.log(error.message);
    }
    ```
